### ISSUE TITLE
[Bug] Core throws HeartbeatTimeoutNotSet when activity heartbeats and no heartbeat timeout is configured

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-core#109]
**Describe the bug**
As described in title, `record_activity_heartbeat` throws when there's no heartbeat timeout configured.
https://github.com/temporalio/sdk-core/blob/1ba045005b915495de9052d0ab6c3f2a474828f0/src/lib.rs#L404

It would be better to ignore or simply warn in this case since the activity sending heartbeats is decoupled from the workflow that sets its `ActivityOptions`.

**To Reproduce**
Schedule an activity without a heartbeat timeout.

**Comment by Sushisource** [comment]
For posterity: @bergundy As we discussed it makes sense to solve this by re-routing the error on the lang side. Let me know if we need to do anything else here otherwise you can close/move this.

**Comment by bergundy** [comment]
Agreed, I'll come up with a design for propagating these errors back into the activity.
