### ISSUE TITLE
Fix WFActivation.is_replaying incorrectly reflecting WF state

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-core#127]
I'm merging this despite the incorrectness of the value.
Let's prioritize fixing this since a lot of functionality relies on the `is_replaying` flag.
One thing I'm not sure of is if this flag should be set per activation or per activation job.
@Sushisource @mfateev @vitarb WDYT?

_Originally posted by @bergundy in https://github.com/temporalio/sdk-core/issues/126#issuecomment-853592693_

**Comment by Sushisource** [comment]
For reference: Lang needs this info so it can choose to not emit logs during replay (for example)
