### ISSUE TITLE
[Feature Request] Allow activity to notify workflow while activity is still running

### ISSUE THREAD

**Issue by wxing1292** [temporalio/sdk-core#131]
**Is your feature request related to a problem? Please describe.**

Allow activity to notify workflow while activity is still running, this can be done solely by SDK providing an API allow activity to signal the workflow it belongs to

**Describe the solution you'd like**

the new SDK API should also allow context propagation

**Additional context**

N/A

**Comment by yiminc** [comment]
Isn't that already supported?
func Activity(ctx context.Context) error {
	temporalClient, err := client.NewClient(client.Options{})
	if err != nil {
		return nil
	}
	info := activity.GetInfo(ctx)
	temporalClient.SignalWorkflow(ctx, info.WorkflowExecution.ID, info.WorkflowExecution.RunID, "signalName", "signalData")

// do other things

}

**Comment by mfateev** [comment]
It is doable. But I think it is to provide a helper function that makes it easy.

**Comment by bergundy** [comment]
I'm not sure this issue belongs in core, we can add it lang-side pretty easily.
ATM core doesn't handle the client functionality, that's all done lang-side using a gRPC client.

**Comment by Sushisource** [comment]
Closing since, yeah, this is really a lang thing.
