### ISSUE TITLE
Port recent gRPC fixes from Java SDK

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-core#191]
Go over these issues and make sure we handle this correctly in Core.
- https://github.com/temporalio/sdk-java/pull/709
- https://github.com/temporalio/sdk-java/issues/653
- https://github.com/temporalio/sdk-java/issues/666

**Comment by Sushisource** [comment]
Closing this since the oddness around deadline exceeded doesn't really apply within core since Core's grpc calls aren't initiated by users.

**Comment by bergundy** [comment]
@Sushisource okay, I didn't look too deeply into these, just wanted to make sure we're covered.
Is there anything we need to do for node?
