### ISSUE TITLE
[Feature Request] Reflect workflow task failures in Core

### ISSUE THREAD

**Issue by sw-yx** [temporalio/sdk-core#206]
### Is your feature request related to a problem? Please describe.

some errors are logged only in Temporal Web, some errors are only logged in the terminal. its confusing to check two places when developing.

### Describe the solution you'd like

passthrough workflow task failures as WARN in terminal

### how to test

- try to write a naughty workflow (eg as of right now, use WeakMap) and execute it
- error would show up in the web ui, but not in the terminal

### Additional context

slack discussion https://temporaltechnologies.slack.com/archives/C01FT8U10GK/p1634677730404700

**Comment by Sushisource** [comment]
This does indeed happen now, just didn't see this bug.
