### ISSUE TITLE
[Bug] sticky task poller should specify TaskQueueKind::Sticky

### ISSUE THREAD

**Issue by yiminc** [temporalio/sdk-core#223]
When frontend received polling request, it needs to decide which partition to forward to. The kind on the request is what frontend use to decide if this is a sticky queue or a normal queue. When it is a sticky queue, its name is used to decide which matching engine owns the queue. If it is a normal queue, an extra random partition is picked and then decide which matching owns that partition.
Partition count is defined by dynamic config, and default to 4. Which means it is 4x cost in turns of server resource of normal queue compare to sticky queue.

**Comment by Sushisource** [comment]
Already resolved by https://github.com/temporalio/sdk-core/pull/221
