### ISSUE TITLE
[Feature Request] Make protos consistent and in same package

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#247]
### Is your feature request related to a problem? Please describe.

Protos in `protos/local/` are inconsistently named and are difficult to work with in some languages do to sharing a directory but being unnecessarily put into separate packages.

### Describe the solution you'd like

Put protos of the same directory into the same package (or move each proto to its own directory more reflective of its package). Not only does this help some code generation (it's nice when your protos are in the same dir that your gen'd code is too, but conflicts abound in languages that leverage proto packages for language packages), but it also makes sense from a discoverability perspective (most protos in the wild have the import dir reflect part of the package, not the import file).

There is also no reason to have two of the same `Failure` types for example.

Also disambiguate the names and properly qualify them. It makes little sense to have `coresdk.activity_task.Start` and `coresdk.child_workflow.ChildWorkflowResult`. While changing the latter to `Result` would technically fix this inconsistency, changing the former to `ActivityStart` would be clearer.

IMO we should change the proto package to `temporal.sdk.core` (can suffix `.v1` if you _really_ want).

Fix all the other little inconsistencies (e.g. change `WFActivation` to `WorkflowActivation`).

### Additional context

I can take this on myself soon.

I am planning on making a single gRPC service like:

```
service Core {
  rpc Stream(stream StreamRequest) returns (stream StreamResponse);
}
```

But we need the protos cleaned up first.

**Comment by Sushisource** [comment]
> (or move each proto to its own directory more reflective of its package).

Makes sense to me. I think the packages are fine as is (we can rename to `temporal.sdk.core.xxx` too). I don't want to put them all in the same package. 

> There is also no reason to have two of the same Failure types for example.

If you're referring to the ones that just wrap the temporal failure, we can probably just eliminate and unwrap them. They used to have more in them I think but that became unnecessary. We can add wrappers back if ever needed.

> changing the former to ActivityStart would be clearer.

I suppose so, but I question if this is really necessary. It's going to require quite a bit of obnoxious renaming in Core and TS.


> I can take this on myself soon.

Let's make sure we're actually agreed on what we want to do before that

**Comment by cretz** [comment]
Works for me. I don't have strong opinions. Breaking out to single-file directories is fine too.
