### ISSUE TITLE
[Feature Request] Reduce required surface area of mock client

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-core#258]
Right now the `ServerGatewayApis` trait is too broad. Core only needs a subset of the functionality internally, and what it requires there is the actual surface area that should be mocked.

The trait should be split up into sub-traits, and only the sub-trait that Core makes use of needs to be mocked. This would allow for more easily extending the client without needing to go pointlessly update mocks.

A long time ago we made the decision that we wanted to accept simpler parameters rather than the raw protos, too. This may be a good time to revisit that. The client meant for end-user consumption can wrap the traits which can operate in terms of the raw protos.

**Comment by cretz** [comment]
@Sushisource - There are a couple use cases of that gRPC client - for core's internal and for caller use. I think it makes plenty of sense to have a core-specific idiomatic client API trait w/ your own params and limited surface (though often the proto params are good enough here like they are for other core calls).

But, where you instantiate this higher-level client backed by gRPC, I think we need a way to still get the raw gRPC trait from there (or maybe the raw gRPC client is what is provided, but it's better to have the high-level client "close"/"drop" handle closing the gRPC conn). So yeah, a `Client` trait with what core needs and a runtime gRPC-based impl in a struct which provides access to the pure gRPC client iface would be nice.

I'm half-tempted to tell new SDK clients not to communicate with gRPC directly but always use the core client just to keep config and connection count centralized (becomes a big deal on gRPC load balancing, cert mgmt, etc). But that's a different topic for a different day.
