### ISSUE TITLE
[Feature Request] Add fields to StartWorkflow

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-core#273]
Currently, `StartWorkflow` has:

https://github.com/temporalio/sdk-core/blob/bcca27258775ceb1100f409f0cc40984218cdf3f/protos/local/temporal/sdk/core/workflow_activation/workflow_activation.proto#L67-L82

There are a lot of `WorkflowExecutionStartedEventAttributes`:

https://github.com/temporalio/api/blob/e82978c745a07fb8820348ad77b1d02e226d182e/temporal/api/history/v1/message.proto#L48

Some of them would be helpful to expose to user, like `last_completion_result`:

https://github.com/temporalio/sdk-typescript/issues/485

**Comment by Sushisource** [comment]
I don't really want to pass the entire attributes wholesale as that can potentially be a rather large copy operation (and I think muddies up this API).

That said no reason we can't add more stuff.

I can add that one, and please list anything else you think I should add while I'm at it @lorensr

**Comment by cretz** [comment]
> One thing from Go that I didn't find in WorkflowExecutionStartedEventAttributes is workflow_start_time—wondering if that should be added to TS and where it comes from.

That's not on the attributes, but instead on the event itself as `event_time`.
