### ISSUE TITLE
Workflow execution reset fails with error

### ISSUE THREAD

**Issue by eplarson** [temporalio/sdk-core#284]
### What are you really trying to do?

I’m running into an issue trying to reset a workflow. I’m currently evaluating Temporal and one of the requirements for us is to be able to just restart a workflow execution manually. The use case is (perhaps):
1. A 3rd party system has a bug and our workflow fails
2. They fix the bug
3. Now we just need to start it over and try again with original arguments.

### Describe the bug

I’m able to run both `tctl workflow reset` and `resetWorkflowExecution` from the Typescript SDK and get a happy response with a new run id, but my worker then fails with this error:

```
thread 'core' panicked at 'Workflow machines must exist, we just created/updated them: WorkflowMissingError { run_id: "07cd4497-3a3c-4694-996a-1bf195bfffa7" }', sdk-core/core/src/workflow/workflow_tasks/mod.rs:359:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Warning: neon::sync::Root leaked during a panic
```

Restarting the worker yields the same result. The failure occurs before attempting the first activity or launching any child workflows.

If I terminate the new execution, then restart the worker and kick off a new workflow execution using `start()` from within the app, everything is fine.

The failed workflow (code below) tries to run 3 child workflows, one of which always fails (this is part of my test scenario).

### Minimal Reproduction

Workflows:
```typescript
export async function dispatchWebhooks(tenantId: string, eventId: string, event: Event<any>): Promise<void> {

  const subscriptions = await fetchWebhookSubscriptions(tenantId, eventId);

  const childHandles: ChildWorkflowHandle<any>[] = [];
  for (const subscription of subscriptions) {
    const childHandle = await startChild(sendWebhook, {
      args: [subscription.url, subscription.headers ?? {}, JSON.stringify({ eventId, ...event })],
      workflowId: "webhook-sub-" + subscription.id,
    });

    childHandles.push(childHandle);
  }

  await Promise.all(childHandles.map(it => it.result()));
}

export async function sendWebhook(url: string, headers: { [header: string]: string }, data: string): Promise<void> {
  await sendWebhookPost(url, headers, data);
}
```

Activities:
```typescript
{
  fetchWebhookSubscriptions: async (tenantId: string, eventId: string) => {
    const subscriptions = await webhookSubscriptionRepo.find({
      org: { id: orgId },
      event: eventId,
      status: WebhookSubscriptionStatus.ACTIVE,
    });

    return subscriptions;
  },
  sendWebhookPost: async (url: string, requestHeaders: { [header: string]: string }, requestBody: string) => {
    let response: AxiosResponse;

    response = await axios.post(url, requestBody, {
      headers: requestHeaders,
      timeout: 10000, // 10 seconds
      transformResponse: r => r,
    });
  },
}
```

### Environment/Versions

- OS and processor: MacOS, x86
- Temporal Version: 1.14.0, Typescript SDK
- Running Temporal via docker-compose

### Additional context

[Slack discussion](https://temporalio.slack.com/archives/C02MTL0GEKH/p1646959797703019)

**Comment by Sushisource** [comment]
@eplarson Thanks for this! If you are able to include the history that goes along with these reproductions, and what event you were targeting when you ran reset, that'd help a bunch too.
