### ISSUE TITLE
[Feature Request] Make telemetry non-global

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#285]
### Is your feature request related to a problem? Please describe.

Currently initialization and use of telemetry is global which is rough on lang impls.

### Describe the solution you'd like

Make the Telemetry non-global (and if lang impls still want static/global they can). Maybe this would just make `GlobalTelemDat` visible and not have a static lifetime as a result of `telemetry_init` and be accepted in client and maybe worker configs, but I have not looked deeply into the code.

**Comment by Sushisource** [comment]
Essentially dupe of https://github.com/temporalio/sdk-core/issues/384
