### ISSUE TITLE
[Feature Request] Support for HTTP CONNECT proxies

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#309]
### Is your feature request related to a problem? Please describe.

gRPC implementations in JS, Go, and Java all support the `GRPC_PROXY`/`HTTP_PROXY` env vars from https://github.com/grpc/grpc/blob/master/doc/environment_variables.md which allow proxying via `HTTP CONNECT` based proxies, but I can find no such support in https://github.com/hyperium/tonic.

### Describe the solution you'd like

Ideally we could contrib support, but in the absence of that, we may need to call out somewhere that gRPC proxy environment variables are not supported for TypeScript workers and that Envoy or another separate proxy should be used.

This issue is just investigatory to confirm what we do and don't support here.

**Comment by 7eben** [comment]
Hi guys.
Is there any workaround available to be able to use a proxy in the grpc connection to Temporary? I am using the python sdk and can confirm what is said in this ticket. Proxy configuration environment variables are being ignored.
