### ISSUE TITLE
[Feature Request] More capabilities on ContinueAsNewWorkflowExecution command

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#372]
### Is your feature request related to a problem? Please describe.

Python user at https://github.com/temporalio/sdk-python/issues/103 wants `retry_policy` for continue as new.

### Describe the solution you'd like

Add `retry_policy` and anything else we think we might want from `temporal.api.command.v1.ContinueAsNewWorkflowExecutionCommandAttributes` onto `coresdk.workflow_commands.ContinueAsNewWorkflowExecution`.

Also, please confirm that:
> Unless noted otherwise, unset or default field values will re-use the issuing workflow's values.

is accurate for the continue as new command (server doesn't carry these values over for us).

**Comment by Sushisource** [comment]
>  (server doesn't carry these values over for us).

Not entirely true. Looking at the code, some things are, some things aren't:
https://cs.github.com/temporalio/temporal/blob/aadbbacf1a84e1d2c0970842c4e92175a90a3b59/service/history/workflow/mutable_state_impl.go#L1437

Which is weird. Retry policy in particular seems obviously like it should carry over without leaning on SDK for that, which it looks like Go does, but Java does not (fyi @Spikhalskiy)

:man_shrugging: I'll make them carry over too
