### ISSUE TITLE
[Feature Request] Support delta aggregation temporality in Otel metrics

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#399]
### Is your feature request related to a problem? Please describe.

NewRelic at https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-metrics/#otel-histogram needs to let users use `DELTA` temporality instead of `CUMULATIVE`. See https://github.com/open-telemetry/opentelemetry-specification/blob/ce50e4634efcba8da445cc23523243cb893905cb/specification/metrics/sdk_exporters/otlp.md#opentelemetry-metrics-exporter---otlp for the spec on it.

### Describe the solution you'd like

We should have a otel metrics option to set the aggregation temporality which should continue to default to cumulative. I believe this is done in the Rust library via an aggregate selector option (which seems removed from the config pipeline in 0.11.0?) and it looks like we have our own `AggregatorSelector` that we'd have to plug that into. I can help research at a deeper level if needed.

When complete, the TypeScript and Python SDKs should expose this option.

**Comment by Sushisource** [comment]
@cretz 
This is pretty easy and I already have updates prepared for the underlying libs. https://github.com/tokio-rs/tracing just released which is what I was waiting for.

Will get to it this week most likely
