### ISSUE TITLE
[Bug] Workflow and Activity Metrics seem lossy

### ISSUE THREAD

**Issue by rupalivohra** [temporalio/sdk-core#419]
### What are you really trying to do?

We are trying to leverage the Temporal core metrics to build out monitors and dashboards.

### Describe the bug

We've noticed that a few metrics are reporting less frequently than they should be. Specific metrics where we've noticed this: `temporal_activity_execution_failed` ([Slack](https://temporalio.slack.com/archives/C01DKSMU94L/p1664838261279999)) and `temporal_workflow_completed`. We've found that metrics incremented from Workflow and Activity interceptors (TS SDK) are showing us roughly expected numbers, but the `temporal_` metrics are vastly underreporting them.

Here are screenshots of graphs that subtract interceptor-based metrics from temporal-based ones. Notice how far below 0 the results are.

#### Activity
`temporal_activity_execution_failed`
![Screen Shot 2022-10-18 at 2 34 57 PM](https://user-images.githubusercontent.com/5040637/196549330-3bc061a8-0463-49de-b686-5184167d265e.png)

#### Workflow

`temporal_workflow_failed`
![Screen Shot 2022-10-18 at 2 35 40 PM](https://user-images.githubusercontent.com/5040637/196549428-269b756e-09ee-4652-b723-0b03542bec2d.png)

`temporal_workflow_completed`
![Screen Shot 2022-10-18 at 2 39 36 PM](https://user-images.githubusercontent.com/5040637/196549964-1d87fd76-2432-45a8-bafc-00b87be87f20.png)

### Minimal Reproduction
See [Draft PR](https://github.com/temporalio/samples-typescript/pull/201)

### Environment/Versions

- Temporal Version: TS SDK: 1.4.2, but we experienced the same thing on 1.0.1.

**Comment by Sushisource** [comment]
Thanks for the detailed info. I'll look into this and see if maybe there's some sampling going on by default that shouldn't be.

It'd help me to know:
What is your export configuration - where are you exporting to, what protocol, are there middlemen, etc?

**Comment by rupalivohra** [comment]
> What is your export configuration - where are you exporting to, what protocol, are there middlemen, etc?

Theoretically we should be exporting to an OTel collector on grpc, which then forwards metrics to our DD Agent (also on grpc). I say theoretically because the docs from OTel were not great at the time we set this up, and there aren't a lot of examples to go off of, but given that we've been seeing metrics come through at all, we assumed that was working fine.

Would it be helpful to share our OTel config?

**Comment by Sushisource** [comment]
Yes it would. I believe the collector may do some sampling, but hopefully not by default. Feel free to DM it to me on slack if you don't want to post it here.

**Comment by rupalivohra** [comment]
DM-ed!

**Comment by Sushisource** [comment]
For any observers:

The otel collector config in use had sampling options enabled, which I suspect is the reason. Once Rupali gets a chance to verify the behavior without those options, we'll proceed.

**Comment by Sushisource** [comment]
@rupalivohra Did you get a chance to try this out?

**Comment by Sushisource** [comment]
Closing this due to staleness. Please open again if you verify it's not b/c of collector settings.
