### ISSUE TITLE
[Feature Request] Session API

### ISSUE THREAD

**Issue by alex-dixon** [temporalio/sdk-core#424]
### Is your feature request related to a problem? Please describe.

I'm writing workflows using the Typescript SDK and would like to be able to download, modify, and upload files reliably and efficiently.

### Describe the solution you'd like

The Session API in the Go SDK seems a good fit for use cases exactly like this.
https://github.com/temporalio/samples-go/tree/main/fileprocessing

Users don't need to do much more than they would with non-session-based workflows and activities. Deploy activities and workflows in any configuration. If you want to route requests to the same worker, you can opt-in by writing a few lines of code using the SDK.

### Additional context

The [sticky activity Typescript example ](https://github.com/temporalio/samples-typescript/tree/main/activities-sticky-queues) shows how to achieve this by coordinating dynamic task queue names between workflows and activities. This appears to require users to coordinate the deployment of workers, possibly implementing some sort of partitioning and load balancing strategy in order to scale them.

Prior feature request in sdk-typescript
https://github.com/temporalio/sdk-typescript/issues/388

**Comment by Sushisource** [comment]
We're unlikely to add session support, at least in it's existing form, to Core - so I'm closing this for now. The [most current TS example](https://github.com/temporalio/samples-typescript/tree/main/worker-specific-task-queues) doesn't require you to deploy any additional workers - if this still doesn't suffice let us know.

If it doesn't, and we have a number of such requests, we may add a session-like concept, but likely with some refinements and we'll open something new to track that.
