### ISSUE TITLE
[Feature Request] Add temporal-cli ephemeral server and deprecate temporalite

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#451]
### Describe the solution you'd like

`temporal_sdk_core::ephemeral_server` has stuff for Temporalite right now. We are going to replace it with Temporal CLI which is now available at temporal.download. We should deprecate (not yet remove) Temporalite and make equivalent functions for Temporal CLI.

**Comment by Sushisource** [comment]
Was done in https://github.com/temporalio/sdk-core/pull/489
