### ISSUE TITLE
[Feature Request] Support custom tags/labels in TelemetryOptions

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#467]
### Is your feature request related to a problem? Please describe.

People need a way to set tags/labels to all metrics (global is the only current requirement, nothing lower level yet)

### Describe the solution you'd like

Support providing metrics tags/labels to be passed with `TelemetryOptions`

**Comment by ytaben** [comment]
@cretz Is there anyone working on this at the moment?
If not - I'm willing to take a stab.

We need this functionality in order to correlate core sdk metrics with the actual services that perform them (we can partially do it via namespace but it's sometimes too generic)

**Comment by Sushisource** [comment]
@ytaben I'm not working on it at the moment, you're welcome to make a PR :)
