### ISSUE TITLE
[Feature Request] Dynamic client for workers

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#477]
### Is your feature request related to a problem? Please describe.

Users want to be able to change client options on running worker

### Describe the solution you'd like

~Initially we can start with exposing https://docs.rs/tonic/latest/tonic/transport/struct.Channel.html#method.balance_channel somehow via the Core client. Ideally this accepts most of the abstraction we already have in client options for the connection-specific params (would make sense to break up ClientOptions from ConnectOptions since only the latter can be pushed at runtime). Then lang can expose the capacity size and change mechanisms for users to push endpoint changes.~

EDIT: Updated title/description. We just need to be able to replace the client on the running worker for common use cases, e.g. updating endpoint or changing TLS options or something. Needs to do so without interrupting poll. For other non-worker client-change needs, users can just use new clients.

**Comment by andrey-dubnik** [comment]
Hi, is it still a plan to move forward with this approach (we have discussed exactly this use case during the Replay catch-up)?

**Comment by cretz** [comment]
There are discussions at https://github.com/temporalio/sdk-core/issues/565 for custom resolvers. I do not understand how "Replay catch-up" relates to client target host/endpoint. If wanting to discuss, feel free to join us on Slack or the forums.
