### ISSUE TITLE
Add search attribute upsert on patch calls

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-core#492]
Each patch call should include a command to upsert the `TemporalChangeVersion` search attribute, including the patch ID if it didn't previously exist in the attribute.

If the attribute size would be exceeded by such an upsert, log a warning and drop the new ID.

**Comment by cretz** [comment]
> If the attribute size would be exceeded by such an upsert, log a warning and drop the new ID.

Hrmm, I wonder if the better approach would be to log a warning and drop the oldest IDs in the keyword list until it's back under size with this new ID.

**Comment by Quinn-With-Two-Ns** [comment]
We discussed both approaches and thought not adding new IDs the lesser of two evils. Mostly because dropping old IDs is dangerous for users, and you most likely have to drop more then 1 old ID for a new one so you loose more information .
