### ISSUE TITLE
[Feature Request] Permit the removal + change of adjacent deprecated patches

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-core#535]
### Is your feature request related to a problem? Please describe.

User had 2 consecutive patches in history `deprecatePatch('patch-1')` followed by `patched('patch-2')` and deployed a change removing the first deprecated patch while deprecating patch-2 and tripped the check in Core that verifies that a patch ID doesn't change during replay.

### Describe the solution you'd like

Ideally, it should be possible to make this change. A couple options:

* When it comes to nondeterminism checking specifically for deprecated patches, if there is a patch-id conflict, assume that this was because of the removal of a previously-adjacent deprecated patch, and allow it.
* Allow patches to be emitted / applied in any order. This is generally safe (since we perform lookahead anyway, and activated patches are sent in a batch for a given WFT), but a more invasive change.

**Comment by Sushisource** [comment]
@rupalivohra For now you should be able to do this as long as you only change one patch at a time. I believe (I haven't had time to confirm this with tests yet though) that this problem only arises if you make simultaneous changes to two adjacent patches.

**Comment by rupalivohra** [comment]
> this problem only arises if you make simultaneous changes to two adjacent patches.

Unfortunately it's difficult to guarantee that there aren't two `deprecatePatch()` calls in all cases, and safer to simply not delete the code given that there's no recovery from the bad state.
