### ISSUE TITLE
[Bug] Worker running which encounters an unknown workflow type will exit

### ISSUE THREAD

**Issue by bdbelevate** [temporalio/sdk-core#558]
### What are you really trying to do?
I'm trying to run a worker using the (alpha) rust SDK so I'm not sure if this is a bug or is just not supported. But currently if a worker is running and an unknown workflow type is encountered on the same task queue, then the worker will exit with the error `Workflow type {workflow_type} not found`

### Describe the bug
When a worker is running and an unknown workflow type is encountered on the same task queue, then the worker will exit with the error `Workflow type {workflow_type} not found`

This happens in this line of code:

https://github.com/temporalio/sdk-core/blob/master/sdk/src/lib.rs#L405

Is this intended behavior and if so, what is the suggested solution? Or is this simply unimplemented at this stage.

### Minimal Reproduction
1. Start a worker using the rust lib.
1. Create a workflow that has a different workflow type then what you defined.
1. The worker will exit.

**Comment by Sushisource** [comment]
@bdbelevate This just isn't implemented right now. It should fail the workflow task instead. You're welcome to make a PR if you're interested :)
