### ISSUE TITLE
[Feature Request] Move ephemeral server behind feature flag

### ISSUE THREAD

**Issue by h7kanna** [temporalio/sdk-core#559]
### Is your feature request related to a problem? Please describe.

As ephemeral_server is only used for testing, Can it be moved into a separate crate to reduce deps in the core and optimize compilation time for user code for using client and worker?

### Additional context

I am trying to optimize compilation time for worker code, and zip dependency of ephemeral_server is big contributor

**Comment by cretz** [comment]
> As ephemeral_server is only used for testing

It's not only used for testing. It's used by all official users of the core crate today. All SDKs leverage this.

**Comment by h7kanna** [comment]
Oh, I am not aware that it is used in non-test code in other SDKs. I only looked at its usage in tests.
Ya, it being behind the default feature should work.

**Comment by h7kanna** [comment]
@cretz , I created PR to add the feature and made it default.

**Comment by cretz** [comment]
> Oh, I am not aware that it is used in non-test code in other SDKs

https://typescript.temporal.io/api/classes/testing.TestWorkflowEnvironment, https://python.temporal.io/temporalio.testing.WorkflowEnvironment.html, and https://dotnet.temporal.io/api/Temporalio.Testing.WorkflowEnvironment.html are all powered by it.

Thanks for the PR! Will let @Sushisource review.

**Comment by h7kanna** [comment]
Seems like the change to add as 'default' does not work because of the missing cargo feature in stable Rust :pensive:

https://github.com/rust-lang/cargo/issues/8366
https://github.com/rust-lang/cargo/issues/5015

**Comment by h7kanna** [comment]
@cretz @Sushisource 

Unfortunately, due to 'feature unification in cargo workspace', we cannot add a feature and add it in default and also can ignore the features with 'no-default-feature' or 'default-feature = false' in a user crate.

I also created another PR https://github.com/temporalio/sdk-core/pull/561 without default, But as mentioned [above](https://github.com/temporalio/sdk-core/issues/559#issuecomment-1563483643) this will need changes to existing SDK code 😔.

Anyways, I am just putting it here if you want to consider this in the future as it is contributing significant time to compilation in Rust-based worker code.

<img width="2476" alt="Screenshot 2023-05-25 at 6 50 58 PM" src="https://github.com/temporalio/sdk-core/assets/2949492/3e080525-ecdf-4f45-bd21-211152da650f">

**Comment by cretz** [comment]
This is quite a bit to just avoid the zip dependency. I wonder if there's another way we can tackle that dependency need.
