### ISSUE TITLE
[Feature Request] Custom "resolver" support

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#565]
### Is your feature request related to a problem? Please describe.
Go and Java gRPC implementations support custom resolvers so users can fail over to different IPs/hosts, but core does not support this. Tonic [does not support it directly](https://github.com/hyperium/tonic/issues/1146) but does suggest a connector can be used.

### Describe the solution you'd like
`temporal_client::ClientOptions` should allow some form of custom connector or resolver callback or something that can allow us to customize the connection that is occurring but without being too complicated hopefully. Could accept a connector but have helper/wrapper for simple resolver connector so that we don't have to mess w/ complexities of connectors.

This request may overlap with #378.

**Comment by dandavison** [comment]
It looks like introducing https://github.com/TrueLayer/ginepro might be the right next step here. I'm looking into it.

**Comment by cretz** [comment]
Hrmm, there still may be value in general purpose resolver override and not specific to what that library does. I wonder if we can take lessons from that library yet still provide general resolver customization.

**Comment by dandavison** [comment]
In case it's useful in the future, there's a WIP branch integrating ginepro here: https://github.com/dandavison/temporalio-sdk-core/tree/565-ginepro
