### ISSUE TITLE
[Feature Request] Support for HTTP CONNECT proxies

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#591]
### Describe the solution you'd like
People need to be able to supply a `HTTP CONNECT` proxy to the client. Tonic/hyper doesn't have native support, but there is [a library](https://github.com/tafia/hyper-proxy) and a [sample](https://github.com/hyperium/hyper/blob/master/examples/http_proxy.rs).

**Comment by josh-berry** [comment]
Duplicate of #309
