### ISSUE TITLE
Differentiating fatal and per-workflow / other non-fatal errors

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-core#61]
As of right now, all errors returned from the Core interface are in one enum, listed here:

```rust
pub enum CoreError {
    /// [Core::shutdown] was called, and there are no more replay tasks to be handled. You must
    /// call [Core::complete_task] for any remaining tasks, and then may exit.
    ShuttingDown,
    /// Poll response from server was malformed: {0:?}
    BadDataFromWorkProvider(PollWorkflowTaskQueueResponse),
    /// Lang SDK sent us a malformed completion: {0:?}
    MalformedCompletion(TaskCompletion),
    /// Error buffering commands
    CantSendCommands(#[from] SendError<Vec<WFCommand>>),
    /// Couldn't interpret command from <lang>
    UninterpretableCommand(#[from] InconvertibleCommandError),
    /// Underlying error in history processing
    UnderlyingHistError(#[from] HistoryInfoError),
    /// Underlying error in state machines: {0:?}
    UnderlyingMachinesError(#[from] WFMachinesError),
    /// Task token had nothing associated with it: {0:?}
    NothingFoundForTaskToken(Vec<u8>),
    /// Error calling the service: {0:?}
    TonicError(#[from] tonic::Status),
    /// Server connection error: {0:?}
    TonicTransportError(#[from] tonic::transport::Error),
    /// Failed to initialize tokio runtime: {0:?}
    TokioInitError(std::io::Error),
    /// Invalid URI: {0:?}
    InvalidUri(#[from] InvalidUri),
    /// State machines are missing for the workflow with run id {0}!
    MissingMachines(String),
}
```

Most of these are not fatal. In fact, probably the only fatal error here that should cause lang sdk to give up entirely is `TokioInitError`, and maaaybe `CantSendCommands`, which is specific to a workflow, but if it happens something very wrong has happened (other workflows might continue working but that one never will). All other errors are either transient network problems (ex tonic errors), expected (`ShuttingDown`), bad data from the server or the lang sdk, or are specific to some individual workflow.

So, we need a way to make that more explicit. A few options:

## Nested enums
This is probably the most natural and obvious option

Break up `CoreError` into this top level enum, and create new sub-enums
```rust
pub enum CoreError {
    Fatal(FatalError),
    WorkflowError {
        run_id: String,
        error: WorkflowError
    }
    ServerError(ServerError), // Bad data received from server
    LangSDKError(LangSDKError) // Bad data given to us from lang
}
pub enum FatalError { .. }
pub enum WorkflowError { .. }
// etc
````

## Function based approach
We'd keep all the errors at the top level, and use functions implemented on the enum to indicate which ones are fatal or per workflow, etc. This is a bit more ergonomic for the insides or core when constructing errors, and potentially on the lang side when it wants to match for some specific error. This also allows errors to be of more than one category. Ex the `CantSendCommands` error could be both fatal, and a workflow error. That's kinda nice.

```rust
impl CoreError {
    pub fn is_fatal(&self) -> bool {
        /// returns true if it's a fatal error
    }
    pub fn is_workflow_error(&self) -> Option<String> {
        /// returns workflow's run id if the error is a workflow error
    }
    // for server / bad data errors, etc.
}
```

Now that I've written this I'm sorta leaning towards the second option.

Not explicitly mentioned already, for all workflow errors we need to include the run id in the error enum variant.

Thoughts?

**Comment by bergundy** [comment]
Let's think about which of these errors lang should be notified of.
The question is which ones of those are actionable by lang.
Maybe core should pass this information with tasks, for instance for deleting a workflow core would give the error as the reason.

**Comment by Sushisource** [comment]
Ah, right, I completely spaced on that option. I think we should almost certainly do that in the cases where it makes sense. It will whittle down some of the top-level errors.

**Comment by Sushisource** [comment]
@bergundy So, in the process of doing this, pushing workflow errors into tasks is nice when possible -- but errors with the workflow can also occur when *completing* a task, so ultimately they still need to be returned synchronously in that case. Theoretically we could just return the error in the next task but that feels super icky if the problem was caused by completing the task.

**Comment by Sushisource** [comment]
Forgot to close this with that merge. We still have some stuff to do here, but we'll need to discover what errors we can better handle first.
