### ISSUE TITLE
[Feature Request] OpenTelemetry HTTP API support

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-core#820]
### Describe the solution you'd like

Currently we only support OTLP over gRPC, but users like https://github.com/temporalio/sdk-python/issues/647 use systems that (surprisingly) don't support OTLP gRPC.

**Comment by Chengdyc** [comment]
I'm interested in this as well. We're trying to publish SDK metrics to Datadog using Otel. We have an OTLP endpoint set up but for reasons unknown (we've been working with Temporal and Datadog support for some time to figure this out with no success), the integration is not working, so we would like to use HTTP to publish SDK metrics instead. thanks.

**Comment by clintonb** [comment]
I just discovered (was reminded) that Temporal only uses gRPC for metrics. We recently switched over to HTTP collectors to start collecting data from browsers. We wanted to avoid maintaining two collectors/pathways to debug, so opted to update all internal services to use HTTP. It's taken me two weeks to realize we missed something...Temporal. 🤦🏾 

It would be great if Temporal supported both HTTP and gRPC so we can simplify our configuration and have more flexibility around how we deploy collectors (e.g., sidecars vs gateways).

**Comment by iand675** [comment]
That's not an accurate statement to my knowledge. Tracing also works with gRPC for at least some languages. Source: I am the Haskell ecosystem OTel maintainer.

**Comment by clintonb** [comment]
> That's not an accurate statement to my knowledge. Tracing also works with gRPC for at least some languages. Source: I am the Haskell ecosystem OTel maintainer.

@iand675 who are you responding to? No one is denying that tracing doesn’t work via gRPC. We are requesting additional support for HTTP.
