### ISSUE TITLE
[Feature Request] Support building other SDKs inside other corporate build systems.

### ISSUE THREAD

**Issue by hailg** [temporalio/sdk-core#837]
### Is your feature request related to a problem? Please describe.

In this ticket, I'm using Python SDK as example, but I think the problem will also apply for other SDK that refer to the sdk-core Rust package. 

So I'm working in an organization where we have our own crate registry. This crate registry will regularly mirrors the crates.io. We also have our own build system for Rust. And that build systems will use our crate registry only. Our build servers won't be able to connect to the internet to pull anything from crates.io

We also have the same constraint for Python, we have our own registries for Python packages. In order to use Temporal SDK, I will need to import and build this package locally in our build system. However, I cannot build the Python SDK because the sdk-core is not publish to crates.io, so it didn't imported automatically into our crate registry. This will fail the build of the Python package.

### Describe the solution you'd like

Can we publish this sdk-core to crates.io? Or any other plans that can support us to build the Python SDK without connecting to crates.io?

Thanks a ton.

**Comment by cretz** [comment]
> However, I cannot build the Python SDK because the sdk-core is not publish to crates.io, so it didn't imported automatically into our crate registry

This dependency isn't obtained from crates.io in Python SDK build, it's in the repo cloned as a submodule. All Rust code for this repository is local to the Python SDK build. It does have dependencies of course that use crates.io which should support your general Rust building approach.

**Comment by hailg** [comment]
Ah got it, in that case, let me try to investigate more. Thanks for the infor @cretz :)

**Comment by cretz** [comment]
:+1: Closing issue for now, but will monitor
