### ISSUE TITLE
Unifying Logging / Metrics w/ OpenTelemetry between Core & Lang

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-core#85]
We've discussed the desire to unify logging across core/lang.

Right now, core uses https://github.com/tokio-rs/tracing to simultaneously perform traditional logging functions, while also generating OpenTelemetry traces.

When we consider unifying these concerns across the language barrier, we really want to do two things:

1. Have consistent "traditional" logging output - IE: What you'd see in the console / a log file.
2. Pass tracing context across the language barrier

For 1, one option (possibly better option described below) is to expose a `log` function from core which takes a `level` parameter, a `span` parameter, a `message` parameter, and optionally a series of key/value pairs to be logged (all logging is structured). Then, lang side has to translate it's logging interface to the core logging interface in whatever way feels most natural/idiomatic and pass logging through to core. The core implementation of that function then constructs an https://tracing-rs.netlify.app/tracing/struct.event corresponding to the passed in parameters.

If there's something more automatic we could do here I'm all ears but nothing comes to mind.

For 2, is seems best for `poll_workflow_task` and `poll_activity_task` to return a `Span` as defined here https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L57 by OpenTelemetry. Then, lang can convert that into the `Span` type that the tracing library it has chosen to use uses, and proceed from there to pass it around and create new child spans, etc. It would then pass it / such spans back into the logging interface described above as the `span` parameter.

While writing the above, I realized there probably is a more elegant option here. The core side can provide an OpenTelemetry "Collector" https://opentelemetry.io/docs/concepts/data-collection/ which the lang side will need to provide an implementation for. Then, ideally, lang simply uses it's opentelem library, registering the custom collector which is core. On the core side, the collector is just a pass through to tokio tracing. Lang would be expected to disable all output, relying on core to collect the logs/traces and output them as console/file/tracing etc. This is more work up front, and possibly per-lang, but also feels substantially less hacky. Unfortunately, I think the spans from 2 still need to be passed into lang so that what it's doing can be associated with certain workflow/activity tasks.

**Comment by mfateev** [comment]
I like the approach where lang can set a sink for log and any other telemetry. This way lang can fully control how the log output is filtered and reported. If the sink is not set the core can use default output which may be useful to troubleshoot the lang side.

**Comment by bergundy** [comment]
First of all, I think we can agree that we want to use open-telemetry for tracing purposes.
I also agree with Maxim that that we should let lang SDK users bring their own logger and metrics solution.
The downside to this approach is that it requires considerable work in each lang SDK.

One thing that comes to mind when thinking of the implementation is that since the core->lang interface asynchronous (in the node SDK, using a queue to pass messages between threads) and might cause tracing events for a single span to be emitted out of order - in case lang emits an event for the same span before it receives an older event for the same span from core, I don't know if that's an issue or not.

**Comment by Sushisource** [comment]
I do not thing lang should handle tracing. I think core should act as a collector for tracing events and deal with reporting them to wherever they're being shipped to.

I think it *does* make sense to create a logging sink on the lang side, which core can duplicate tracing events to if the user wants to see them in the logs.

Having lang act as the tracing sink I think duplicates effort a bunch because unlike logging I don't think we have the expectation that users should be able to bring their own tracing framework. We can allow them to specify different collectors that core can report to pretty easily.

**Comment by mfateev** [comment]
The tracing framework at least in Java is pluggable. Some customers want opentracing, others want opentelemetry or some other.

**Comment by Sushisource** [comment]
@mfateev Are you just getting at it may not be worth customizing the tracing framework? I agree. I think we should just support OpenTelemetry (OpenTracing has merged with it) -- all I was getting at is the user needs a way to be able to say where the traces *go* and we should probably support multiple backends for that (which is easy for us to support). So, they can specify in a config file or whatever that they'd like to use Jaeger or Zipkin, etc, etc.

**Comment by Sushisource** [comment]
Starting to get into this. The problem with our situation is that OTEL basically does not imagine the situation where you might want to collect data across a language boundary and have that data being generated on both sides. Essentially it assumes all data-creators are independent services (not unreasonably). Here's a high-level overview of the options I can think of so far:

1. Require users to run the [OTEL collector](https://github.com/open-telemetry/opentelemetry-collector) along with their worker when they want traces/metrics. Both core and lang point at it with exporters, everything gets collected there and then exported to the destination of their choice. This is definitely the most inline with what OTEL expects things to look like, and is almost certainly the path of least resistance on our side. Effectively we are treating core/lang as independent services here (which they sorta are). The obvious downside is that the user has to run this extra binary/sidecar/whatever. 
1. Somehow (and I'm not sure this is possible without a *lot* of work) embed a OTEL "collector" into the lang side. Core uses the https://docs.rs/opentelemetry-otlp/0.9.0/opentelemetry_otlp/ exporter to push all it's data there, and then lang users can configure whatever OTEL exporter they want to send the combined data to. The plus here is there's no extra process. The downside is this seems really rough to get working, and has to be done per-lang. Alternatively the collector could be embedded in Core, which at least means we only have to do it once, but then the exporter needs to be configured in Rust or a config file.
1. Don't originate any metrics or traces from inside Core. If all traces & metrics only exist on the lang side, then all core needs to do is attach additional information to the spans which lang originates. Then it doesn't need to export OTEL data at all. This is nice and simple, but has the glaring downside that there are probably a lot of metrics that only exist inside Core we'd like to collect.


Regardless of the above options, it seems likely that we'll probably want to handle just logging output through a different channel, so that users can still see it if they aren't exporting OTEL data. That's pretty simple though, at least, and can just consist of Core streaming its log info to lang on a constant basis where lang then just turns it into it's configured log output.

I think I'm most in favor of 1. Implementing our own collector per-lang seems like an enormous amount of work. Running a collector is trivial if the user is already using docker, and even if they aren't there are statically compiled binaries available.

**Comment by Sushisource** [comment]
Can use this as a list of metrics we'll want to add: https://github.com/temporalio/sdk-go/blob/master/internal/common/metrics/constants.go

Also see https://github.com/temporalio/dashboards/blob/master/dashboards/sdk.json for highest priority ones

**Comment by sw-yx** [comment]
discussion ongoing https://temporaltechnologies.slack.com/archives/C01FG4BRQVB/p1630361300031600

**Comment by bergundy** [comment]
Great summary @Sushisource.

I'm leaning towards option 5, I've done this in the `@temporalio/interceptors-opentelemetry` package to shuffle traces from the Workflow isolate to the Node.js isolate.

Overall it was ~80 LOC:

https://github.com/temporalio/sdk-node/blob/cd10cb4b187a6a733770502fbca32b9dcd2d2244/packages/interceptors-opentelemetry/src/workflow/span-exporter.ts#L8

https://github.com/temporalio/sdk-node/blob/cd10cb4b187a6a733770502fbca32b9dcd2d2244/packages/interceptors-opentelemetry/src/worker/index.ts#L65

It'll probably be a bit longer in Rust but we only have to write it once.

**Comment by Sushisource** [comment]
@bergundy My concern with 5 isn't the export part which we only have to write once in Rust, that's easy. It's the import part in Lang. The deserialization is probably also pretty easy, but the attaching the imported data part is what's unclear and might be quite a bit of work. Not immediately obvious to me how that's happening in your example. Is the line here https://github.com/temporalio/sdk-node/blob/cd10cb4b187a6a733770502fbca32b9dcd2d2244/packages/interceptors-opentelemetry/src/worker/index.ts#L75 all that's needed to re-export the spans? If so, then yeah this looks doable for sure. I'll at least try it out.

**Comment by bergundy** [comment]
I don't understand what you mean by attaching the imported data?
The line you pointed at is where spans get re-exported

**Comment by Sushisource** [comment]
I'm gonna try out 5 then since it seems more doable than initially thought. Will try to get prototype going today.

**Comment by Sushisource** [comment]
Have decided on option 1 (using the OTel collector) as option 5 is much to great of a maintenance burden and chafes strongly against OTel's design principles.
