### ISSUE TITLE
[Feature Request] Make compilation work on Mac M1.

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-core#90]
When compiling the node SDK, I got the following error with an M1 CPU.

```
npm ERR! error: failed to run custom build command for `temporal-sdk-core v0.1.0 (/Users/bergundy/temporal/sdk-node/packages/worker/native/sdk-core)`
npm ERR!
npm ERR! Caused by:
npm ERR!   process didn't exit successfully: `/Users/bergundy/temporal/sdk-node/packages/worker/native/target/release/build/temporal-sdk-core-de4edef256dc9a6c/build-script-build` (exit code: 1)
npm ERR!   --- stderr
npm ERR!   Error: Custom { kind: Other, error: "failed to invoke protoc (hint: https://docs.rs/prost-build/#sourcing-protoc): Bad CPU type in executable (os error 86)" }
```

This is easily fixed by installing protobuf with `brew install protobuf` and exporting `PROTOC=$(which protoc)` (See tonic [docs](https://docs.rs/prost-build/0.7.0/prost_build/#sourcing-protoc)).
This is of course not critical but it would be nice to be able to have compilation "just work".

**Comment by Sushisource** [comment]
Protoc is always required now all the time, closing this since it's just a given you're gonna need it for general temporal dev.
